import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#000' },
  container: { flex: 1, padding: 24, justifyContent: 'center' },
  title: { fontSize: 24, fontWeight: '600', textAlign: 'center', marginBottom: 20, color: '#fff' },
  videoPicker: {
    height: 100,
    borderRadius: 16,
    backgroundColor: '#1c1c1e',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    overflow: 'hidden',
  },
  videoPreview: { width: '100%', height: '100%' },
  videoPickerText: { color: '#8E8E93', fontSize: 15, fontWeight: '500' },
  videoPickerSubtext: { color: '#8E8E93', fontSize: 12, marginTop: 4 },
  changeVideoBadge: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  changeVideoBadgeText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  label: { color: '#8E8E93', fontSize: 13, fontWeight: '600', marginBottom: 6, marginLeft: 2 },
  input: {
    height: 48,
    borderRadius: 12,
    backgroundColor: '#1c1c1e',
    paddingHorizontal: 14,
    marginBottom: 16,
    color: '#fff',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  descriptionInput: {
    height: 56,
    borderRadius: 12,
    backgroundColor: '#1c1c1e',
    paddingHorizontal: 14,
    paddingTop: 12,
    marginBottom: 16,
    color: '#fff',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    textAlignVertical: 'top',
  },
  pickerWrapper: {
    borderRadius: 12,
    backgroundColor: '#1c1c1e',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    marginBottom: 24,
    overflow: 'hidden',
  },
  picker: { color: '#fff' },
  pickerItem: { color: '#fff' },
  primaryButton: {
    height: 48,
    borderRadius: 12,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: { color: '#000', fontWeight: '600', fontSize: 16 },
  buttonDisabled: { opacity: 0.5 },
  closeButton: {
    position: 'absolute',
    top: 60,
    left: 16,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.3)',
    zIndex: 10,
  },
  closeButtonText: { color: '#fff', fontSize: 24, fontWeight: '700', lineHeight: 24 },
});
